name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::testthat
            any::devtools
            any::htmlwidgets
            any::jsonlite
            any::pkgdown

      - name: Install npm dependencies
        run: npm ci

      - name: Run JavaScript tests
        run: npm run test:js

      - name: Run R tests
        run: npm run test:r
